import { createReactComponent } from "@ui5/webcomponents-base";
import DialogClass from "@ui5/webcomponents/dist/Dialog.js";
import TextClass from "@ui5/webcomponents/dist/Text.js";
import TitleClass from "@ui5/webcomponents/dist/Title.js";
import PanelClass from "@ui5/webcomponents/dist/Panel.js";
import IconClass from "@ui5/webcomponents/dist/Icon.js";
import CheckBoxClass from "@ui5/webcomponents/dist/CheckBox.js";
import LinkClass from "@ui5/webcomponents/dist/Link.js";
import ButtonClass from "@ui5/webcomponents/dist/Button.js";

const Dialog = createReactComponent(DialogClass);
const Text = createReactComponent(TextClass);
const Title = createReactComponent(TitleClass);
const Panel = createReactComponent(PanelClass);
const Icon = createReactComponent(IconClass);
const CheckBox = createReactComponent(CheckBoxClass);
const Link = createReactComponent(LinkClass);
const Button = createReactComponent(ButtonClass);

function App() {
  const dialogRef = useRef(null);
  const acceptButtonRef = useRef(null);
  const checkboxRef = useRef(null);
  const termsPanelRef = useRef(null);

  const handleAcceptButtonClick = (e) => {
    if (!hasScrolledToBottom || !checkboxRef.current.checked) {
    e.preventDefault();
    }
  };

  const handleCheckboxMousedown = (e) => {
    if (!hasScrolledToBottom) {
    e.preventDefault();
    }
  };

  const handleCheckboxChange = () => {
    acceptButtonRef.current.disabled = !(hasScrolledToBottom && checkboxRef.current.checked);
  };

  const handleTermsPanelScroll = () => {
    const scrollTop = termsPanelRef.current.scrollTop,
    clientHeight = termsPanelRef.current.clientHeight,
    scrollHeight = termsPanelRef.current.scrollHeight,
    atBottom = scrollTop + clientHeight >= scrollHeight - 1;
    if (atBottom) {
    hasScrolledToBottom = true;
    acceptButtonRef.current.disabled = !checkboxRef.current.checked;
    }
  };

  return (
    <>
      <!DOCTYPE html>
      <html lang="en">
      <head>
      	<meta charset="UTF-8" />
      	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
      	<link rel="stylesheet" href="./main.css" />
      	<title>Sample</title>
      </head>
      <body>
      	<Dialog id="dialog" ref={dialogRef} state="Information" headerText="Information">
      		<br />
      		<Text>
      			Please read the following information carefully and accept these terms and conditions:
      		</Text>
      		<br />
      		<Title level="H5">Terms of use</Title>
      		<br />
      		</Text>
      		<Panel id="termsPanel" ref={termsPanelRef} onScroll={handleTermsPanelScroll} expanded={true}>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}><strong>SAP AI TERMS</strong></Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>These SAP AI Terms (“Terms”) apply to artificial intelligence features and technologies provided with SAP</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>Cloud Services (“AI Technology”). “Output” means any content generated by AI Technology as output,</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>based on the data provided to AI Technology, including Customer Data, and data used to train AI</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>Technology.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>1. <strong>ACCEPTABLE USE</strong></Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>1.1. Customer will use AI Technology responsibly, safely, in a legally compliant manner, and in accordance</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>with the Documentation, and will not use AI Technology to:</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(a) Promote or facilitate illegal activities or unlawful actions;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(b) Facilitate fraudulent actions;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(c) Attempt unauthorized access to a system, property, or information;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(d) Generate content that contains or promotes violence, hate speech, or harassment, or insults or</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>demeans a person;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(e) Generate sexually explicit content;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(f) Distribute malware or spam;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(g) Contravene regulatory safety policies;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(h) Track people without consent;</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(i) Falsely impersonate an individual; or</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>(j) Mine cryptocurrency.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>1.2. SAP may limit or suspend access to Output or AI Technology in the event these Terms are violated or for</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>non-compliance with Documentation.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>1.3. Customer will not circumvent or bypass protective measures made available by SAP or a third-party,</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>including, but not limited to, those intended to help prevent copyright infringement, data breaches, or</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>security incidents.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>1.4. Customer will not <Icon name="information" accessibleName="Info" title="More info"/> use AI Technology or Output to develop, train, or improve other AI services or AI</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>models, unless explicitly permitted by SAP, or (ii) use web scraping, web harvesting, or web data extraction</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>methods to extract data from AI Technology or Output.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>2. <strong>OUTPUT</strong></Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>2.1. Notwithstanding any recommendation contained within Output, reliance on Output is in Customer’s</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>discretion. Customer will assess Output (including by code scanning, security scanning, human review,</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>and human oversight and correction) before using or relying on the Output for any purpose. Customer will</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>also utilize any review tools and filtering options that SAP makes available.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>2.2. AI Technology consists of emerging technologies and, given the nature of such technologies, their use</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>may result in incorrect, biased, unfair, or inaccurate Output and/or Output that may be nonsensical or</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>untruthful in relation to certain sources.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>2.3. In addition Output may not qualify for intellectual property protection; similar or the same Output may be</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>produced by AI Technology to similar requests from different customers, and Customer’s rights to Output</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>may not be enforceable against other users of AI Technology. Customer’s ownership in Output is subject</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>to SAP’s and/or its licensor’s ownership rights in the Cloud Service, SAP Materials, and data used to train</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>AI Technology (“Pre-Existing Materials”). Customer is granted a right to use, and only will use, Pre-</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>Existing Materials in Output to the same extent as Customer is permitted to use the Cloud Service.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>3. <strong>ADDITIONAL TERMS</strong></Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>The legal framework applicable to and the interpretation of competent courts and authorities regarding the</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>use of AI technologies is evolving. If a change in law or the interpretation of a competent court or authority</div>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>results in <Icon name="information" accessibleName="Info" title="More info"/> SAP’s inability to offer an AI Technology or (ii) Customer’s inability to use an AI Technology</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>in a legally compliant manner, SAP may reduce the scope of use (e.g., if the use of an AI Technology</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>becomes prohibited, SAP may cease offering such AI Technology in a given country ) or remove such AI</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>Technology altogether. The same applies where SAP can no longer provide an AI Technology provided</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>by a third-party, because such third-party discontinues availability of such AI Technology or changes its</Text>
      			<br />
      			<br />
      			<br />
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>SAP AI Terms enMEE.v.10-2024 Page 2 of 2</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>service terms or documentation in contradiction to the Agreement or another way that prevents SAP from</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>further offering such AI Technology.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>3.2. AI Technology may include AI models, technologies or features licensed from third-parties that require</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>SAP to pass through additional terms. Customer will comply with such pass-through terms as made</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>available by SAP at https://www.sap.com/about/trust-center/agreements.html, within the Documentation,</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>or otherwise. When SAP introduces new AI Technology, SAP may provide additional terms or make</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>updates to the terms, that apply to Customer’s use of such AI Technology.</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>3.3. SAP does not commit to the use of specific AI models in a Cloud Service even if Customer may be able</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>to choose between different AI models when using the Cloud Service. SAP reserves the right to add,</Text>
      			<Text style={{ paddingTop: "0.15rem", paddingBottom: "0.15rem" }}>remove, or exchange AI models, in its sole discretion, at any time.</Text>
      		</Panel>
      		<br />
      		<div style={{ display: "flex", alignItems: "center" }}>
      			<CheckBox id="termsCheck" />
      			<Text>
      				I hereby confirm I have read and agreed to
      				<Link href="https://www.sap.com" target="_blank" />&lt;document link 1&gt;</Link> and
      				<Link href="https://www.sap.com" target="_blank" />&lt;document link 2&gt;</Link>.
      			</Text>
      		</div>
      		<br />
      		<div slot="footer" style={{ display: "flex", justifyContent: "flex-end", width: "100%", alignItems: "center", gap: "0.25rem" }}>
      			<Button design="Emphasized" className="dialogCloser" id="acceptButton" ref={acceptButtonRef} onClick={handleAcceptButtonClick} disabled={true}>Accept</Button>
      			<Button className="dialogCloser">Dismiss</Button>
      		</div>
      	</Dialog>
      	<script type="module" src="main.js"></script>
      </body>
      </html>
    </>
  );
}

export default App;
