import { createReactComponent } from "@ui5/webcomponents-base";
import LabelClass from "@ui5/webcomponents/dist/Label.js";
import PopoverClass from "@ui5/webcomponents/dist/Popover.js";
import TableCellClass from "@ui5/webcomponents/dist/TableCell.js";
import TableHeaderCellClass from "@ui5/webcomponents/dist/TableHeaderCell.js";
import TableRowClass from "@ui5/webcomponents/dist/TableRow.js";
import TextClass from "@ui5/webcomponents/dist/Text.js";

const Label = createReactComponent(LabelClass);
const Popover = createReactComponent(PopoverClass);
const TableCell = createReactComponent(TableCellClass);
const TableHeaderCell = createReactComponent(TableHeaderCellClass);
const TableRow = createReactComponent(TableRowClass);
const Text = createReactComponent(TextClass);

function App() {

  return (
    <>
      <TableHeaderCell id="produtCol" width="200px">
    					<Label required={true}>Product</Label>
    					<ui5-table-header-cell-action-ai slot="action" id="aiActionProduct"></ui5-table-header-cell-action-ai>
    				</TableHeaderCell>
    <!-- playground-fold -->
    				<TableHeaderCell id="supplierCol">Supplier</TableHeaderCell>
    				<TableHeaderCell id="dimensionsCol" importance="-1">Dimensions</TableHeaderCell>
    				<TableHeaderCell id="weightCol" popin-text="Weight">Weight</TableHeaderCell>
    <!-- playground-fold-end -->
    				<TableHeaderCell id="priceCol" min-width="100px" horizontal-align="End" popin-text="Price in Popin" sort-indicator="Descending">
    					<Label>Price</Label>
    					<ui5-table-header-cell-action-ai slot="action" id="aiActionPrice"></ui5-table-header-cell-action-ai>
    				</TableHeaderCell>
    <!-- playground-fold -->
    			</ui5-table-header-row>
    			<TableRow row-key={0}>
    				<TableCell><Label><b>Notebook Basic 17</b><br />HT-1001</Label></TableCell>
    				<TableCell><Label>Smartcards</Label></TableCell>
    				<TableCell><Label>29 x 17 x 3.1 cm</Label></TableCell>
    				<TableCell><Label style={{ color: "#2b7c2b" }}><b>4.5</b> KG</Label></TableCell>
    				<TableCell><Label><b>1249</b> EUR</Label></TableCell>
    			</TableRow>
    			<TableRow row-key={1}>
    				<TableCell><Label><b>Notebook Basic 15</b><br />HT-1000</Label></TableCell>
    				<TableCell><Label>Very Best Screens</Label></TableCell>
    				<TableCell><Label>30 x 18 x 3 cm</Label></TableCell>
    				<TableCell><Label style={{ color: "#2b7c2b" }}><b>4.2</b> KG</Label></TableCell>
    				<TableCell><Label><b>956</b> EUR</Label></TableCell>
    			</TableRow>
    			<TableRow row-key={2}>
    				<TableCell><Label><b>Notebook Basic 18</b><br />HT-1002</Label></TableCell>
    				<TableCell><Label>Technocom</Label></TableCell>
    				<TableCell><Label>32 x 21 x 4 cm</Label></TableCell>
    				<TableCell><Label style={{ color: "#2b7c2b" }}><b>3.7</b> KG</Label></TableCell>
    				<TableCell><Label><b>290</b> EUR</Label></TableCell>
    			</TableRow>
    		</ui5-table>
    		<!-- playground-fold-end -->
    		 <Popover style={{ width: "25rem" }} id="generatedByAIPopover">
    			<Text>
    				This content was partially or fully generated by artificial intelligence (AI) technologies.<br /><br />
    				The AI-generated content may contain inaccuracies due to using multiple information sources. Verify results before use.
    			</Text>
    		 </Popover>
    </>
  );
}

export default App;
