name: Deploy Website Preview

on:
  pull_request:
    types: [opened, closed, synchronize, reopened]
    branches:
      - asdf-main # to exlude it from the workflow
    paths:
      # Website-specific changes
      - 'packages/website/**'
      # Documentation changes
      - 'docs/**'
      - '*.md'
      - 'README.md'
      # Component CSS/TS changes that affect documentation
      - 'packages/base/src/**/*.css'
      - 'packages/base/src/**/*.ts'
      - 'packages/ai/src/**/*.css' 
      - 'packages/ai/src/**/*.ts'
      - 'packages/compat/src/**/*.css'
      - 'packages/compat/src/**/*.ts'
      - 'packages/fiori/src/**/*.css'
      - 'packages/fiori/src/**/*.ts'
      - 'packages/main/src/**/*.css'
      - 'packages/main/src/**/*.ts'
      # Exclude test files to avoid unnecessary builds
      - '!**/*.spec.ts'
      - '!**/*.test.ts'
      - '!**/test/**'

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install dependencies
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        yarn install

    - name: Update version.md for PR
      run: |
        mkdir -p packages/website/static
        touch packages/website/static/version.md
        echo "PR #${{ github.event.number }} - $(git log -1 --format='%h %s')" > packages/website/static/version.md
        echo "Branch: ${{ github.head_ref }}" >> packages/website/static/version.md
        echo "Commit: $(git rev-parse HEAD)" >> packages/website/static/version.md

    - name: Build website
      env:
        DEPLOYMENT_TYPE: "preview"
        PR_NUMBER: "${{ github.event.number }}"
      run: |
        yarn ci:deploy:preview

    - name: Deploy to PR subfolder
      uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: gh-pages
        folder: packages/website/build
        target-folder: pr-${{ github.event.number }}
        clean: false
        single-commit: true

    - name: Comment PR with preview link
      uses: actions/github-script@v7
      with:
          github-token: ${{ secrets.UI5_WEBCOMP_BOT_GH_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-${prNumber}/`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });

            const existingComment = comments.find(comment => 
              comment.body.includes('🚀 Preview deployment') && 
              comment.user.login === 'ui5-webcomponents-bot'
            );

            const commentBody = `🚀 **Preview deployment ready:** ${previewUrl}

            The preview will be updated automatically when you push new commits to this PR.
            `;

            if (!existingComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            }

  cleanup-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
        contents: write  # Required for gh-pages deployment
    steps:
        - name: Checkout gh-pages
          uses: actions/checkout@v4
          with:
            ref: gh-pages
            token: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Remove PR folder and commit
          run: |
            if [ -d "pr-${{ github.event.number }}" ]; then
                rm -rf "pr-${{ github.event.number }}"
                
                # Configure git with GitHub Actions bot credentials
                git config user.name "${{ secrets.UI5_WEBCOMP_BOT_NAME }}"
                git config user.email "${{ secrets.UI5_WEBCOMP_BOT_EMAIL }}"
                
                # Stage and commit changes
                git add .
                if git diff --staged --quiet; then
                  echo "No changes to commit"
                else
                  git commit -m "chore: cleanup preview for PR #${{ github.event.number }}"
                  git push
                fi
            else
                echo "Preview folder pr-${{ github.event.number }} not found"
            fi
